### ISSUE TITLE
Add support for Crunched DDS images

### ISSUE THREAD

**Issue by andburn** [andburn/hs-art-extractor#6]
card texture HS9-007_M

**Comment by FardHast** [comment]
Hi, @andburn! I'm not sure if it's a right place to talk but anyway. I know how to extract images from .unity3d files but I need to connect their ID with an actual card ID. A file CardArtDefs.xml really helps with that, but the question is: How to update it myself? Is it created by you or it exists in game files? You're good programmer, definitely a LOT better than me, but I don't need to rely on someone, when new patch comes out. I really hope it doesn't sound rude for you. I'm doing a HS related minigame in browser btw. 
PS: Sorry for bad English.

**Comment by andburn** [comment]
@FardHast
Hi, this program generates the mapping found in `CardArtDefs.xml` from the game files. Its not that easy to explain how it works, you could try and read the code but its a bit of a mess. The quick explanation is that there are objects in the `cards0.unity3d` file called `CardDefs` one for each card, these contain the texture name to use.
You could also look at `generate_card_textures.py` in [HearthSim/HearthstoneJSON](https://github.com/HearthSim/HearthstoneJSON), it does the same thing in a nicer way.

Also, if you want to talk more about this stuff or you own project join the HearthSim irc or discord channels, plenty of people to help you out there, see https://hearthsim.info/join/

**Comment by andburn** [comment]
actual issue fixed (*filthy hack*) with c025d4a0f881
