### ISSUE TITLE
Same cards

### ISSUE THREAD

**Issue by verng** [andburn/hs-art-extractor#7]
Pictures are the same. Though should be different.
![2016-12-22_201935](https://cloud.githubusercontent.com/assets/17193436/21434144/fd9e07fa-c883-11e6-8efa-bcac9ba9c358.png)

![2016-12-22_202009](https://cloud.githubusercontent.com/assets/17193436/21434161/0b6847b0-c884-11e6-815c-bbf459a1746a.png)

**Comment by FardHast** [comment]
Working as intended. One is card, second is enchantment.

**Comment by andburn** [comment]
Yep, what @FardHast said.
This should only happen if you use the `--no-filters` option, leave that out and it will skip the enchantments.
